Final/urls.py
from django.urls import path
from . import  views

app_name = 'ruth'
urlpatterns = [
    path('', views.index, name = 'home' ),
    path('index/', views.index, name='index'),
    path('details/<int:person_id>/', views.details, name = 'details'),
    path('failed/', views.failed, name = 'failed'),
    path('home/', views.home, name = 'home'),
    path('file/', views.get_form, name = 'file'),
    path('calendar/', views.calendar, name = 'calendar'),
]

Ruth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('Final.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='Final/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='Final/logout.html'), name='logout'),
    path('reset/', auth_views.PasswordResetView.as_view(template_name = 'Final/resetpassword.html'), name = 'reset'),
    path('resetDone/', auth_views.PasswordResetDoneView.as_view(template_name = 'Final/resetdone.html'), name = 'resetDone'),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.postgres.fields import JSONField

# Create your models here.

#
class Job(models.Model):
    name=models.CharField(max_length=40)
    role=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    date_updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Resumes(models.Model):
    name = models.CharField(max_length=100, verbose_name="Full Name")
    email = models.EmailField(max_length = 100, unique = True, verbose_name="Email")
    file = models.FileField(upload_to='resume', verbose_name="Resume")
    position = models.ForeignKey(Job, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Applying Position")
    date_pub = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = "Resumes"
        verbose_name = "Resume"

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_pub <= now

    was_published_recently.admin_order_field = 'date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.email


class Resume_Information(models.Model):
    owner = models.OneToOneField(Resumes, on_delete=models.CASCADE)
    pdf_text = models.TextField()
    status = models.BooleanField(default=False)
    rating=models.FloatField()
    date_pub = models.DateTimeField(default=timezone.now)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_pub <= now

    was_published_recently.admin_order_field = 'date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    # returning the name of the resume owner
    # def name(self):
    #     resume = Resumes.objects.filter(id=self.owner).get()
    #     return resume.email
    #
    # name.short_description = "Resume Owner"

    def __str__(self):
        return self.owner.name

    class Meta:
        verbose_name_plural = "Uploaded Resumes"
        verbose_name = "Uploaded Resume"



class Job_Requirement(models.Model):
    job=models.ForeignKey(Job, on_delete=models.CASCADE)
    requirement=models.TextField()

    def __str__(self):
        return self.requirement

class Job_Keyword(models.Model):
    job=models.ForeignKey(Job, on_delete=models.CASCADE)
    keyword=models.CharField(max_length=30)

    def __str__(self):
        return self.keyword

Final/forms.py
from django import forms
from .models import Resumes

class PdfForm(forms.ModelForm):
    class Meta:
        model=Resumes
        exclude=("date_pub", )

        widgets = {'file': forms.FileInput(
            attrs={
                'accept': 'application/pdf, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/msword'})}

    # name = forms.CharField(label = "Name", max_length = 100)
    # email = forms.EmailField(label = "Email")
    # file = forms.FileField(label = "Upload Resume")

Final/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import SimpleUploadedFile
from django.contrib.sessions.models import Session
import datetime
from django.core.files import File


from .forms import PdfForm
from django.utils import timezone
from .models import Resumes, Resume_Information
from . import textExtract
import pandas as pd
import environ
import time

env=environ.Env(
    SLEEP = (int, 0)
)



@login_required(login_url = '/login/')
def home(request):
    sessions = Session.objects.all().count()
    total = Resumes.objects.all().count()
    application = Resume_Information.objects.all().order_by('-date_pub')
    new = Resume_Information.objects.filter(status=False).all().count()

    context = {
        'application': application,
        'total': total,
        'sessions': sessions,
        'new': new
    }
    return render(request, 'Final/index.html', context)


def index(request):
    return render(request, 'index/index.html')

# def success(request):
#     return render(request, 'Final/success.html')

def failed(request):
    return render(request, 'Final/failed.html')

def calendar(request):
    return render(request, 'Final/calendar.html')


def get_form(request):
    if request.method == 'POST':
        form = PdfForm(request.POST, request.FILES)
        if form.is_valid():
            
            try:
                instance=form.save()
            except:
                return HttpResponseRedirect('/failed/')

            else:
                scanned_text=textExtract.pdfFileScan(instance.file.url, instance.name)
                # scanned_text
                total_score = 0.00
                count=0
                for key, value in dict(scanned_text).items():
                    for value in value.values():
                        total_score+=value
                        count+=1

                mean=(total_score/count)
                instance2 = Resume_Information(owner=instance, pdf_text=scanned_text, rating=mean)

                instance2.save()
                content = Resume_Information.objects.filter(owner=instance).get()
                # df=pd.DataFrame(data=scanned_text)
                # table=df.to_html(classes="table")
                table=dict(scanned_text)
                context = {'content': content, 'table':table}
                return render(request, "Final/success.html", context)
            
        else:
            return HttpResponseRedirect('/failed/')

    else:
        form = PdfForm()
        context = {'form': form}
        return render(request, 'Final/pdfForm.html', context)

@login_required(login_url='/login/')
def details(request, person_id):
    person = get_object_or_404(Resume_Information, pk=person_id)
    specifics=eval(person.pdf_text)
    sessions = Session.objects.all().count()
    total = Resumes.objects.all().count()
    application = Resume_Information.objects.all().order_by('-date_pub')
    new = Resume_Information.objects.filter(status=False).all().count()


    context={
        'person':person,
        'specifics':specifics,
        'application': application,
        'total': total,
        'sessions': sessions,
        'new': new
    }
    return render(request, 'Final/detail.html', context)


# def pdfShow(request, url):
#     pdf
#
# def downloadPdf(request, applicant_id):
#     file_path=Resume_Information.objects.get(pk=applicant_id)
#     path=file_path.owner.file.url
#
#     f1=open(path, 'r')

Final/templates/Final/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />

    <title>Resume Analyser | Dashboard</title>

    <!-- Font Awesome Icons -->
    <link rel="shortcut icon" href="{% static 'Final/logo/favicon.png' %}" />
    <link
      rel="stylesheet"
      href="{% static 'Final/plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- overlayScrollbars -->
    <link
      rel="stylesheet"
      href="{% static 'Final/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}"
    />
    <!-- Theme style -->
    <link
      rel="stylesheet"
      href="{% static 'Final/dist/css/adminlte.min.css' %}"
    />
    <!-- Google Font: Source Sans Pro -->
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700"
      rel="stylesheet"
    />
  </head>

  <body
    class="
      hold-transition
      sidebar-mini
      layout-fixed layout-navbar-fixed layout-footer-fixed
    "
  >
    <div class="wrapper">
      <!-- Navbar -->
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"
              ><i class="fas fa-bars"></i
            ></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'ruth:index' %}" class="nav-link">Home</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/" class="nav-link">Admin</a>
          </li>
          {% endif %}
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'logout' %}" class="nav-link">Logout</a>
          </li>
        </ul>

        <!-- SEARCH FORM -->
        <form class="form-inline ml-3">
          <div class="input-group input-group-sm">
            <input
              class="form-control form-control-navbar"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </form>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
          <!-- Messages Dropdown Menu -->
          <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
              <i class="far fa-comments"></i>
              <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              <div class="dropdown-divider"></div>

              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item dropdown-footer"
                >See All Messages</a
              >
            </div>
          </li>
          <!-- Notifications Dropdown Menu -->

          <li class="nav-item">
            <a
              class="nav-link"
              data-widget="control-sidebar"
              data-slide="true"
              href="#"
              ><i class="fas fa-th-large"></i
            ></a>
          </li>
        </ul>
      </nav>
      <!-- /.navbar -->

      <!-- Main Sidebar Container -->
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="index3.html" class="brand-link">
          <img
            src="{% static 'Final/dist/img/AdminLTELogo.png'%}"
            alt="Nyamusi logo"
            class="brand-image img-circle elevation-3"
            style="opacity: 0.8"
          />
          <span class="brand-text font-weight-light"> Cv Validator</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
          <!-- Sidebar user panel (optional) -->
          <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
              <img
                src="{% static 'Final/dist/img/user2-160x160.jpg' %}"
                class="img-circle elevation-2"
                alt="User Image"
              />
            </div>
            <div class="info">
              <a href="#" class="d-block"
                >{% if user %} {{ user.first_name}} {{user.last_name}}{% else %}
                Welcome {% endif %}</a
              >
            </div>
          </div>

          <!-- Sidebar Menu -->
          <nav class="mt-2">
            <ul
              class="nav nav-pills nav-sidebar flex-column"
              data-widget="treeview"
              role="menu"
              data-accordion="false"
            >
              <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
              <li class="nav-item has-treeview menu-open">
                <a href="{% url 'ruth:home' %}" class="nav-link active">
                  <i class="nav-icon fas fa-tachometer-alt"></i>
                  <p>
                    Dashboard
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
              </li>

              <li class="nav-header">EXAMPLES</li>
              <li class="nav-item">
                <a href="{% url 'ruth:calendar' %}" class="nav-link">
                  <i class="nav-icon fas fa-calendar-alt"></i>
                  <p>
                    Calendar
                    <span class="badge badge-info right">2</span>
                  </p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon far fa-image"></i>
                  <p>Gallery</p>
                </a>
              </li>
              <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                  <i class="nav-icon far fa-envelope"></i>
                  <p>
                    Mailbox
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Inbox</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Compose</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Read</p>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
          <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0 text-dark">Your Dashboard</h1>
              </div>
              <!-- /.col -->
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  {% block breadcrumb %} {% endblock %}
                </ol>
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <!-- Info boxes -->
            <div class="row">
              <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box">
                  <span class="info-box-icon bg-info elevation-1"
                    ><i class="fas fa-cog"></i
                  ></span>

                  <div class="info-box-content">
                    <span class="info-box-text">System Traffic</span>
                    <span class="info-box-number">
                      10
                      <small>%</small>
                    </span>
                  </div>
                  <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
              </div>
              <!-- /.col -->
              <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box mb-3">
                  <span class="info-box-icon bg-danger elevation-1"
                    ><i class="fas fa-users"></i
                  ></span>

                  <div class="info-box-content">
                    <span class="info-box-text">Applicants</span>
                    <span class="info-box-number">
                      {% if total %} {{ total }} {% else %} None {% endif %}
                    </span>
                  </div>
                  <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
              </div>
              <!-- /.col -->

              <!-- fix for small devices only -->
              <div class="clearfix hidden-md-up"></div>

              <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box mb-3">
                  <span class="info-box-icon bg-success elevation-1"
                    ><i class="fas fa-clock"></i
                  ></span>

                  <div class="info-box-content">
                    <span class="info-box-text">Active</span>
                    <span class="info-box-number">
                      {% if sessions %} {{sessions}} {% else %} None {% endif %}
                    </span>
                  </div>
                  <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
              </div>
              <!-- /.col -->
              <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box mb-3">
                  <span class="info-box-icon bg-warning elevation-1"
                    ><i class="fa fa-barcode"></i
                  ></span>

                  <div class="info-box-content">
                    <span class="info-box-text">Analyzed</span>
                    <span class="info-box-number">
                      {% if total %} {{total}} {% else %} None {% endif %}
                    </span>
                  </div>
                  <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- This is where the index page goes to -->

            {% block index %} {% endblock %}
          </div>

          <!-- /.col -->
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
      </aside>
      <!-- /.control-sidebar -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <strong>Copyright &copy; 2021 <a href="/">Brian Keari</a>.</strong>
        All rights reserved.
      </footer>
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="{% static 'Final/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'Final/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'Final/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'Final/dist/js/adminlte.js' %}"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="{% static 'Final/dist/js/demo.js' %}"></script>

    <!-- PAGE PLUGINS -->
    <!-- jQuery Mapael -->
    <script src="{% static 'Final/plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>
    <script src="{% static 'Final/plugins/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'Final/plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
    <script src="{% static 'Final/plugins/jquery-mapael/maps/usa_states.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'Final/plugins/chart.js/Chart.min.js' %}"></script>

    <!-- PAGE SCRIPTS -->
    <script src="{% static 'Final/dist/js/pages/dashboard2.js' %}"></script>
  </body>
</html>

Final/templates/Final/detail.html
{% extends './base.html'%}
{% load static %}
{% block breadcrumb %}
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active">Dashboard</li>
{% endblock %}
{% block index %}

<div class = 'container'>
   <div class="alert alert-primary text-center" role="alert">
        <span class="row" style="font-size:30px">
            <span class = "col-md-6">
            {% if person %}
                {{person.owner.name}}
            {% endif %}
            </span>
            <span class="col-md-6">
                Position:
                {% if person %}
                    {{person.owner.position}}
                {% endif %}
            </span>
        </span>
    </div>
    <div>
        {% if person %}
            <div class="row" style="font-size: 25px">
                <div class="col"><span class="badge badge-success">Total Score:</span></div>
                <span class="col">{{person.rating | floatformat:2}}</span>
            </div>
            <br>
            <div class="row">
                <div class="col-sm">
                    <span><h6 class="text-info">Email: </h6></span><span><p>{{person.owner.email}}</p></span>
                </div>

                 <div class="col-sm">
                     <span><h6 class="text-info">Resume: </h6></span><span><a class="btn btn-outline-secondary" href="{{person.owner.file.url}}">{{person.owner.file}}</a></span>
                </div>

            </div>


            {% if specifics %}
            <div class="row">
                 <h3 class="text-center text-primary">Results breakdown</h3>
            <!--<p>{{content.pdf_text}}</p>-->

                        <!--{{table}}-->
                        {% for key, values in specifics.items %}

                                <table class="table">

                                    <thead>
                                    <tr>
                                        <th scope="col">Module</th>
                                        <th scope="col">{{key | title}}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for key,values in values.items %}
                                        <tr>
                                            <td>{{key}}</td>
                                            <td>{{values}}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                        {% endfor %}
                    {% endif %}
                    {% endif %}
                </div>
            </div>

    {% if person %}

    <div>
        <h6 class="text-center">Resume</h6>
        <embed height="500"
                src="{{person.owner.file.url}}" type="application/pdf" width="100%" height="100%">
    </div>
    {% endif %}
</div>
{% endblock %}

Final/templates/Final/failed.html
{% extends './home.html' %}

{% block success %}
    <div class="alert alert-success text-center" role="alert">
      You had already submitted your application
    </div>
{% endblock %}

Final/templates/Final/home.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Resume | home</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href=" {% static 'Final/logo/favicon.png' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=" {% static 'Final/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Final/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Final/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Final/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Final/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Final/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Final/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Final/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Final/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Final/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>


	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'Final/images/bg-01.jpg'%});">
			<div class="wrap-login100">
				<div class="login100-form">
                    {% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-30 p-t-23">
						Applications Resume Handler
					</span>

					{% block success %}
					{% endblock %}

					<div class="container-login100-form-btn">
						<a href="{% url 'login' %}">
						<button class="login100-form-btn">
							Login
						</button>
						</a>
					</div>
					<div class = "container-login100-form-btn" style="padding-top: 2rem">
						<a href="{% url 'ruth:file'%}">
							<button class="login100-form-btn">
							Upload Cv
						</button>
						</a>
					</div>

				</div>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'Final/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Final/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Final/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'Final/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Final/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Final/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'Final/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Final/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Final/js/main.js' %}"></script>

</body>
</html>

Final/templates/Final/logout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Ruth| Logout</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="shortcut icon" type="image/png" href=" {% static 'Final/logo/favicon.png' %}"/>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'Final/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'Final/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  	<link rel="stylesheet" type="text/css" href=" {% static 'Final/vendor/bootstrap/css/bootstrap.min.css' %}">
</head>
<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <p><b>You are </b>Logged Out</p>
  </div>

  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="{% static 'Final/dist/img/user1-128x128.jpg' %}" alt="User Image">
    </div>
    <!-- /.lockscreen-image -->

    <!-- lockscreen credentials (contains the form) -->



    <!-- /.lockscreen credentials -->

  </div>
  <div class = 'lockscreen-item' style="transform: translateX(3rem); text-align:center">
     <a href="{% url 'login' %}">
          <button class="btn btn-primary">
            Login
          </button>
        </a>
  </div>
  <!-- /.lockscreen-item -->
  <div class="help-block text-center">
    click to Login Again
  </div>
  <div class="text-center">
    <a href="{% url 'ruth:index' %}">Head to the Home Page</a>
  </div>


  <div class="lockscreen-footer text-center">
    Copyright &copy; 2020 <b><a  class="text-black">Victor Okinyi</a></b><br>
    All rights reserved
  </div>
</div>
<!-- /.center -->

<!-- jQuery -->
<script src="{% static 'Final/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'Final/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

Final/templates/Final/success.html
{% extends 'home.html' %}

{% block success %}
    <div class="alert alert-success align-center" role="alert">
  Submission Successful
</div>
{% endblock %}